import type { Metadata } from 'next'
import CalculatorClient from './CalculatorClient'
import Footer from '@/components/Footer'
import DotBackground from '@/components/DotBackground'
import Navbar from '@/components/Navbar'
import WhatsAppButton from '@/components/WhatsAppButton'
export const metadata: Metadata = {
  title: 'Website Cost Calculator India (2026) | Web Development Price Estimator',
  description: 'Calculate the exact cost of your website development instantly. Our transparent calculator provides a real-time price estimate for business, e-commerce, and custom websites in India. 100% accurate pricing.',
  keywords: 'website cost calculator india, web development price estimator, how much does a website cost, ecommerce website price india, website development cost calculator',
  alternates: {
    canonical: '/website-cost-calculator',
  },
  openGraph: {
    title: 'Website Cost Calculator India | Web Development Price Estimator',
    description: 'Calculate the cost of your website development instantly. Transparent, no-BS pricing estimation in INR.',
    type: 'website',
  },
}

export default function CalculatorPage() {
  const schemaMarkup = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "SoftwareApplication",
        "name": "WebXCrafting Website Cost Calculator",
        "applicationCategory": "BusinessApplication",
        "operatingSystem": "All",
        "description": "An interactive tool to estimate the cost of web development projects including e-commerce, SaaS, and business websites in India.",
        "offers": {
          "@type": "Offer",
          "price": "0",
          "priceCurrency": "INR"
        }
      },
      {
        "@type": "FAQPage",
        "mainEntity": [
          {
            "@type": "Question",
            "name": "How is the website development cost calculated?",
            "acceptedAnswer": {
              "@type": "Answer",
              "text": "The cost is calculated based on five main factors: The type of website (Business, E-commerce, SaaS), the total number of pages, the complexity of UI/UX design, required addon features (like SEO, Admin Panels, Payment Gateways), and the level of post-launch maintenance required."
            }
          },
          {
            "@type": "Question",
            "name": "Are there any hidden charges?",
            "acceptedAnswer": {
              "@type": "Answer",
              "text": "No. At WebXCrafting, we believe in 100% transparency. The price generated by our calculator is an accurate estimate. Any third-party costs like domain names or server hosting are discussed upfront."
            }
          }
        ]
      }
    ]
  }

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schemaMarkup) }}
      />
      <div style={{ position: 'relative', minHeight: '100vh', background: 'var(--bg)' }}>
        
        {/* Calculator Tool */}
        <div style={{ position: 'relative', zIndex: 50 }}>
          <CalculatorClient />
        </div>

        {/* SEO Rich Text Section */}
        <section style={{ padding: '80px 20px', maxWidth: '1000px', margin: '0 auto', position: 'relative', zIndex: 5, color: '#8892b0' }}>
          <div style={{ background: 'rgba(10,14,28,0.7)', borderRadius: '24px', padding: 'clamp(24px, 5vw, 48px)', border: '1px solid rgba(99,120,255,0.1)', backdropFilter: 'blur(20px)' }}>
            <h2 style={{ fontFamily: 'Syne', fontSize: 'clamp(24px, 4vw, 36px)', color: '#fff', marginBottom: '24px', fontStyle: 'italic', fontWeight: 800 }}>
              How Much Does a <span style={{ color: '#4f6fff' }}>Website Cost</span> in 2026?
            </h2>
            <p style={{ fontSize: '16px', lineHeight: 1.8, marginBottom: '20px' }}>
              Building a professional website is an investment in your business's future. However, pricing in the web development industry can often feel confusing. Our <strong>Website Cost Calculator</strong> is designed to give you a transparent, real-time estimate based on current market standards in India and globally.
            </p>
            
            <h3 style={{ fontSize: '20px', color: '#e8eaf6', marginTop: '32px', marginBottom: '16px', fontWeight: 700 }}>Key Factors Affecting Web Development Costs</h3>
            <ul style={{ listStyleType: 'disc', paddingLeft: '20px', display: 'flex', flexDirection: 'column', gap: '12px', marginBottom: '24px' }}>
              <li><strong>Website Type:</strong> A simple 5-page business website is significantly cheaper than a fully custom E-commerce store or a complex SaaS portal with user authentication.</li>
              <li><strong>Design Complexity:</strong> Standard templates reduce costs, while custom-designed UI/UX with high-end Framer Motion animations require more development time and expertise.</li>
              <li><strong>Add-on Features:</strong> Features like payment gateway integration, advanced on-page SEO, multi-lingual support, and custom admin dashboards directly impact the final price.</li>
            </ul>

            <h3 style={{ fontSize: '20px', color: '#e8eaf6', marginTop: '32px', marginBottom: '16px', fontWeight: 700 }}>Why Use Our Cost Estimator?</h3>
            <p style={{ fontSize: '16px', lineHeight: 1.8 }}>
              Unlike generic agencies that hide their pricing, WebXCrafting provides an upfront estimate instantly. Whether you need a landing page for lead generation or a luxury 3D-animated web application, you can adjust the features in the calculator above and download a customized PDF proposal immediately. No waiting for quotes, no hidden fees.
            </p>
          </div>
        </section>
      </div>
      <style dangerouslySetInnerHTML={{__html: `
        @media (max-width: 900px) {
          .calculator-footer-wrapper { padding-bottom: 90px; }
        }
      `}} />
      <div className="calculator-footer-wrapper">
        <Footer />
      </div>
      <WhatsAppButton />
    </>
  )
}
